version: 0.2
env:
  variables:
    S3_BUCKET: "x"
phases:
  install:
    runtime-versions:
      nodejs: 16
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - npm run build
      - npm run test:ci
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes