version: 0.2
env:
  variables:
    S3_BUCKET: "x"
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      # Update libs
      - apt-get update
      # Headless Chrome
      - apt-get install -y fonts-liberation libasound2 libnspr4 libnss3 libx11-xcb1 xdg-utils libxss1 libappindicator1 libindicator7
      - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      - dpkg -i google-chrome*.deb
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install
      - npm install -g @angular/cli
  build:
    commands:
      - npm run build
      - npm run test:ci
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes